# Generated by Django 6.0.2 on 2026-02-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, help_text='Загрузите постер фильма', null=True, upload_to='posters/', verbose_name='Постер фильма'),
        ),
        migrations.AddField(
            model_name='film',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='Ссылка на YouTube трейлер (например: https://www.youtube.com/watch?v=XXXXX)', max_length=500, null=True, verbose_name='Ссылка на трейлер'),
        ),
    ]
