# Generated by Django 6.0.2 on 2026-02-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0002_film_poster_film_trailer_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='poster_url',
        ),
        migrations.AddField(
            model_name='film',
            name='watch_url',
            field=models.URLField(blank=True, help_text='Ссылка для просмотра фильма', max_length=500, null=True, verbose_name='Ссылка на фильм'),
        ),
    ]
