# Generated by Django 6.0.2 on 2026-02-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0003_remove_film_poster_url_film_watch_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='Прямая ссылка на видеофайл трейлера (MP4)', max_length=500, null=True, verbose_name='Ссылка на трейлер'),
        ),
    ]
