# Generated by Django 6.0.2 on 2026-02-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0004_alter_film_trailer_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='trailer_url',
        ),
        migrations.RemoveField(
            model_name='film',
            name='watch_url',
        ),
        migrations.AddField(
            model_name='film',
            name='trailer_file',
            field=models.FileField(blank=True, help_text='Загрузите видеофайл трейлера в формате MP4', null=True, upload_to='trailers/', verbose_name='Видеофайл трейлера'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, help_text='Загрузите постер фильма (JPG, PNG)', null=True, upload_to='posters/', verbose_name='Постер фильма'),
        ),
    ]
