# Generated by Django 6.0.2 on 2026-02-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0005_remove_film_trailer_url_remove_film_watch_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(blank=True, to='kino_app.genre', verbose_name='Жанры'),
        ),
    ]
